name: pinloc
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  intl: any
  location: any 
  google_maps_flutter: any
  address_search_field: any
  mqtt_client: any
  device_info_plus: any
  rflutter_alert: any
  flutter_local_notifications: any
  # flutter_osm_plugin: ^0.30.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0 

flutter:
  uses-material-design: true
